image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Check code style
        script:
          - docker run --rm -v $PWD:/workspace syncloudsoftech/pinter pint --test
        services:
          - docker
